services:
  frontend:
    container_name: dev-linkloom-frontend
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:8.0
    container_name: dev-linkloom-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev-admin
      MONGO_INITDB_ROOT_PASSWORD: dev-password
      MONGO_INITDB_DATABASE: dev-linkloom-db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db-studio:
    image: mongo-express:1.0.0
    container_name: dev-linkloom-db-studio
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev-admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev-password
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      db:
        condition: service_healthy

volumes:
  mongo-data: {}