global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dev-linkloom'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['frontend:3000']

  - job_name: 'dev-linkloom-db'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['mongo-prometheus:9216']