{
 "title": "MongoDB | Bitnami Exporter",
 "time": { "from": "2025-08-31T05:38:43.751Z", "to": "2025-08-31T05:41:49.452Z" },
 "panels": [
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoDB Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{job=\"dev-linkloom-db\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Read Ops/s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opWorkingTime_reads_ops[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Ops/s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opWorkingTime_writes_ops[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Ops/s",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opWorkingTime_commands_ops[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations per Second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum by (type) (rate(mongodb_ss_opLatencies_ops[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opWorkingTime_reads_latency[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opWorkingTime_writes_latency[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opWorkingTime_commands_latency[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Network Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_numRequests[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Out (B/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_physicalBytesOut[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network In (B/s)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_physicalBytesIn[5m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Database Data Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum by (db) (mongodb_dbstats_totalSize)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "sum by (db) (mongodb_dbstats_storageSize)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Index Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum by (db) (mongodb_dbstats_indexSize)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Object Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "sum by (db) (mongodb_dbstats_objects)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Resident Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 95 },
   "targets": [
    { "expr": "mongodb_ss_mem_resident\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Virtual Memory (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 95 },
   "targets": [
    { "expr": "mongodb_ss_mem_virtual\n", "legendFormat": "__auto" }
   ]
  }
 ]
}