name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  prepare-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker installation
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker run hello-world

      - name: SSH into server and ensure directory exists
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            mkdir -p /usr/local/app/


  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Create ENV for Next.js
        run: |
         echo "${{ secrets.ENV_PRODUCTION }}" > .env.production

      - name: Build frontend and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/production/Dockerfile
          push: true
          tags: |
            nightmarevco/linkloom:latest
            nightmarevco/linkloom:${{ steps.get_version.outputs.version }}

      - name: Build grafana and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: grafana
          file: grafana/Dockerfile
          push: true
          tags: |
            nightmarevco/linkloom-grafana:latest

      - name: Build loki and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: loki
          file: loki/Dockerfile
          push: true
          tags: |
            nightmarevco/linkloom-loki:latest

      - name: Build prometheus and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: prometheus
          file: prometheus/Dockerfile
          push: true
          tags: |
            nightmarevco/linkloom-prometheus:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /usr/local/app/
            echo "${{ secrets.ENV_PRODUCTION }}" > .env
            docker network create linkloom-traefik || true
            docker compose pull
            docker compose up -d